fixtures
arrayOfArrayXML
	^ '<m:reverseArray
xmlns:m="http://www.mars.dti.ne.jp/~umejava/smalltalk/soapOpera/rpc/"
SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENC:Array xsi:type="SOAP-ENC:Array" 
SOAP-ENC:arrayType="SOAP-ENC:Array[2]">
 <item xsi:type="SOAP-ENC:Array" SOAP-ENC:arrayType="xsd:anyType[0]">
 </item>
  <item xsi:type="SOAP-ENC:Array" SOAP-ENC:arrayType="xsd:anyType[3]">
   <item xsi:type="xsd:int">17974494715439249409</item>
   <item xsi:type="xsd:string">aV34fTn/QoILMlilPla2Pw==</item>
   <item xsi:type="xsd:string">20030913T14:26:28 &#43;200</item>
  </item>
</SOAP-ENC:Array>
</m:reverseArray>
'