fixtures
dotNetSharedValuesEnvelopeXML

^'<soap:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:types="urn:WebBookingEngine" xmlns:tns="urn:WebBookingEngine"
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
 <soap:Body soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <types:FindPropertiesIdByLocationResponse>
   <FindPropertiesIdByLocationResult
href="#id1"></FindPropertiesIdByLocationResult>
  </types:FindPropertiesIdByLocationResponse>
  <soapenc:Array id="id1" soapenc:arrayType="xsd:int[37]">
   <Item>22039</Item>
   <Item>22933</Item>
   <Item>23177</Item>
   <Item>23249</Item>
   <Item>23393</Item>
  </soapenc:Array>
 </soap:Body>
</soap:Envelope>'