fixtures
oneSizeArrayReturnEnvelopeDocumentStyleXML

^'<?xml version="1.0" encoding="UTF-8" ?> 
 <env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns0="urn:my.test.com">
 <env:Body>
  <ns0:DataVersionArrayElement>
   <ns0:dataVersion>
    <ns0:country>US</ns0:country> 
    <ns0:build>379</ns0:build> 
   </ns0:dataVersion>
  </ns0:DataVersionArrayElement>
 </env:Body>
 </env:Envelope>'