fixtures
singleReturnEnvelopeDocumentStyleXML

^'<soapenv:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <soapenv:Header>
 </soapenv:Header>
 <soapenv:Body>
  <ns:sampleResponse xmlns:ns="http://service.spring/xsd">
   <ns:return>bareString</ns:return>
  </ns:sampleResponse>
 </soapenv:Body>
</soapenv:Envelope>'